<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-06T18:37:30 IST" name="Suite" finished-at="2025-04-06T18:38:08 IST" duration-ms="37857">
    <groups>
    </groups>
    <test started-at="2025-04-06T18:37:30 IST" name="Test" finished-at="2025-04-06T18:38:08 IST" duration-ms="37857">
      <class name="runnerScripts.TC02_VerificationOfAddEmployee">
        <test-method is-config="true" signature="ConfigReports()[pri:0, instance:runnerScripts.TC02_VerificationOfAddEmployee@74e52ef6]" started-at="2025-04-06T18:37:30 IST" name="ConfigReports" finished-at="2025-04-06T18:37:30 IST" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ConfigReports -->
        <test-method is-config="true" signature="BrowserConfiguration()[pri:0, instance:runnerScripts.TC02_VerificationOfAddEmployee@74e52ef6]" started-at="2025-04-06T18:37:30 IST" name="BrowserConfiguration" finished-at="2025-04-06T18:37:38 IST" duration-ms="7511" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BrowserConfiguration -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:runnerScripts.TC02_VerificationOfAddEmployee@74e52ef6]" started-at="2025-04-06T18:37:38 IST" name="LaunchApplication" finished-at="2025-04-06T18:37:46 IST" duration-ms="8770" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="TC02_AddEmployeeVerification()[pri:0, instance:runnerScripts.TC02_VerificationOfAddEmployee@74e52ef6]" started-at="2025-04-06T18:37:46 IST" name="TC02_AddEmployeeVerification" finished-at="2025-04-06T18:37:58 IST" duration-ms="11267" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at runnerScripts.TC02_VerificationOfAddEmployee.TC02_AddEmployeeVerification(TC02_VerificationOfAddEmployee.java:16)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_AddEmployeeVerification -->
        <test-method is-config="true" signature="CloseApplication()[pri:0, instance:runnerScripts.TC02_VerificationOfAddEmployee@74e52ef6]" started-at="2025-04-06T18:37:58 IST" name="CloseApplication" finished-at="2025-04-06T18:38:05 IST" duration-ms="7416" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseApplication -->
        <test-method is-config="true" signature="CloseBrowser()[pri:0, instance:runnerScripts.TC02_VerificationOfAddEmployee@74e52ef6]" started-at="2025-04-06T18:38:05 IST" name="CloseBrowser" finished-at="2025-04-06T18:38:08 IST" duration-ms="2160" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBrowser -->
        <test-method is-config="true" signature="FlushReport()[pri:0, instance:runnerScripts.TC02_VerificationOfAddEmployee@74e52ef6]" started-at="2025-04-06T18:38:08 IST" name="FlushReport" finished-at="2025-04-06T18:38:08 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FlushReport -->
      </class> <!-- runnerScripts.TC02_VerificationOfAddEmployee -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
